app/smc/pytest/e2e-smoke.py

pyluwen now throws an exception during the detect_chip() call if a PCIE rescan is needed. Handle this exception by rescanning the PCIE bus

app: smc: pytest: rescan PCIE if pyluwen can't detect chip

---

.github/workflows/prepare-zephyr/action.yml
README.md
scripts/requirements.txt
west.yml

* move manifest group filter to manifest file
* remove west update step, since it duplicates zephyr action
* move local python deps to scripts/requirements.txt

ci: simplify prepare-zephyr reusable workflow

---

app/smc/pytest/recovery.py
app/smc/sample.yaml
lib/tenstorrent/bh_arc/init.c
lib/tenstorrent/bh_arc/init_common.h
lib/tenstorrent/bh_arc/status_reg.h
scripts/tt_boot_fs.py

Add a pytest to validate flashing a corrupt image. Note that this PR is blocked until we merge the following fixes:
https://github.com/tenstorrent/luwen/pull/20
https://github.com/tenstorrent/tt-flash/pull/24
Without these changes, tt-flash will hang when trying to flash the original FW while the recovery FW is running (as we don't have a telemetry table)
The PR currently has the pytest tagged so it shouldn't run (because if it does, the card on the CI system won't be flashable)

ci: add pytest to validate flashing a corrupt image

---

doc/release.md

Add a rough document describing the steps in the release process.
This is a mashup of a couple of different release process docs.
https://docs.mcuboot.com/release.html
https://docs.zephyrproject.org/latest/project/release_process.html#tagging

doc: add release process documentation

---

app/smc/pytest/recovery.py

Make some fixes that had not been made in #4.

app: smc: pytest: recovery: prefer pathlib over os.path

---

scripts/requirements.txt

Dependencies can be installed via `pip install -r requirments.txt`.

scripts: requirements: add tt-flash to pip requirements

---

lib/tenstorrent/bh_arc/aiclk_ppm.c
lib/tenstorrent/bh_arc/aiclk_ppm.h
lib/tenstorrent/bh_arc/dvfs.c
lib/tenstorrent/bh_arc/init.c

This was causing an issue where unforcing the frequency with aiclk_ppm disabled caused CMFW to attempt setting an AICLK frequency of 0, which hangs the chip.

tenstorrent: bh_arc: init boot_freq even when aiclk_ppm is disabled

---

lib/tenstorrent/bh_arc/fan_ctrl.c

Otherwise fan_ctrl will hang on these reads.

bh_arc: fan_ctrl should skip reading from harvested GDDR

---

boards/tenstorrent/tt_blackhole/spirom_data_tables/GALAXY/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P100/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P100A/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150A/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150C/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300A_L/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300A_R/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300C_L/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300C_R/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300_L/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300_R/fw_table.txt

This makes sure that all boards of the same type look the same, despite different harvesting configurations.
Note that this setting doesn't actually have any effect until feature_enable.harvesting_en is enabled in the fw_tables.

boards: fw_table: update soft harvesting according to product specs

---

lib/tenstorrent/jtag_bootrom/jtag_bootrom.c

Fixed leftover #if IS_ENABLED preprocessor definitions in jtag_bootrom.c

Updated jtag_bootrom.c to use #ifdef instead of #if IS_ENABLED

---

.github/workflows/build-fw.yml
.github/workflows/hardware-smoke.yml
.github/workflows/prepare-zephyr/action.yml
.github/workflows/release.yml
.github/workflows/run-unit-tests.yml

Make the `prepare-zephyr` workflow reusable across jobs, and use it wherever possible within CI

ci: make `prepare-zephyr` workflow reusable across jobs

---

boards/tenstorrent/tt_blackhole/spirom_data_tables/GALAXY/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/ORION/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P100/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P100A/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150A/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150C/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300A_L/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300A_R/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300C_L/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300C_R/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300_L/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300_R/fw_table.txt

aiclk_ppm is enabled for all p100 and p150.
ddr_train is enabled for all boards, although the flag is currently ignored by FW.
These are the settings that were updated in the internal repo and not reflected here.

fw_table: enable aiclk_ppm and ddr_train flags

---

lib/tenstorrent/bh_arc/dw_apb_i2c.c
lib/tenstorrent/bh_arc/dw_apb_i2c.h
lib/tenstorrent/bh_arc/regulator.c
lib/tenstorrent/bh_arc/regulator.h

Read back regulator initialization programming values to ensure they are written properly. Retry once (per CMD) if programming fails. Aggregate all failures and return error status from `RegulatorInit()`.

bh_arc: regulator: init programming with readback verification

---

lib/tenstorrent/bh_arc/harvesting.c

We want to soft harvest one GDDR when the actual GDDR count is greater than the desired GDDR count.

bh_arc: fix gddr soft harvesting logic

---

lib/tenstorrent/bh_arc/fan_ctrl.c
lib/tenstorrent/bh_arc/gddr.c
lib/tenstorrent/bh_arc/gddr.h
lib/tenstorrent/bh_arc/telemetry.c

This change will check the GDDR telemetry table version and ensure it matches the gddr_telemetry_table.h version. If not, it will log warning message and keep all the GDDR telemetry fields as 0. 
Justification is in case we ever have a mismatch in MRISC and SMC FWs, we don't want to make assumptions that may no longer hold.

bh_arc: Check GDDR telemetry table version

---

app/bmc/src/main.c
include/tenstorrent/bh_chip.h
lib/tenstorrent/bh_arc/cm2bm_msg.c
lib/tenstorrent/bh_arc/cm2bm_msg.h
lib/tenstorrent/bh_arc/telemetry.c
lib/tenstorrent/bh_arc/telemetry.h
lib/tenstorrent/bh_arc/throttler.c
lib/tenstorrent/bh_chip/bh_chip.c

Send input current data from BMC to SMC in signed int 16.16 format. Provide input current as a float to the board power throttler.

ina228: fix input current formatting

---

.github/workflows/build-fw.yml
.github/workflows/build-native.yml
.github/workflows/compliance.yml
.github/workflows/copyright-check.yml
.github/workflows/hardware-long.yml
.github/workflows/hardware-smoke.yml
.github/workflows/license-check.yml
.github/workflows/run-unit-tests.yml

We ideally would prefer to see runner history on `main` instead of just on PR history. This will allow us to more easily determine the last successful CI run, and thus help narrow-down PRs that cause regressions, without having to do a full git bisect.
Additionally, run checks whenever PRs (backported bugfixes) have been made or merged to version branches.
Additionally, disable fast-failing for hardware tests so that we can see which platforms pass or fail tests independently. Without this, if one platform fails tests, the job is cancelled for all platforms.

ci: ensure workflows run after push to main

---

lib/tenstorrent/bh_arc/dvfs.c
lib/tenstorrent/bh_arc/dw_apb_i2c.c

This PR fixes two issues blocking CI:
- Add bus timeouts to *all* I2C operations that can hang, and recover the I2C bus when they do. This is admittedly a bit of voodoo- all I can say is without this change I saw the CMFW hanging during I2C transactions during init, and with it I don't. Solves issues like those seen here: https://github.com/tenstorrent/tt-zephyr-platforms/actions/runs/14138868875/job/39616640036
- Increase the scheduling deadline for DVFS polling to 10ms. This was done because it appears that DVFS polling itself takes over 1 ms, so rescheduling it this frequently was causing VUART to fail.

lib: tenstorrent: add I2C timeouts on all operations, and fix DVFS library issue with VUART

---

lib/tenstorrent/bh_arc/pvt.c

This reduces the amount of time spent polling in GetAvgChipTemp() which should help reduce FW busy-ness. This temporary fix allows logging to still be functional when aiclk_ppm/dvfs is enabled.

bh_arc: pvt: reduce TS polling time by reducing resolution

---

app/smc/src/main.c
lib/tenstorrent/bh_arc/init.c
lib/tenstorrent/bh_arc/status_reg.h

It is potentially unsafe to enable aiclk_ppm if the regulator init fails. Report this scenario via LOG_ERR and into a status register.
This needs #49 to be merged first.

bh_arc: do not enable aiclk_ppm if regulator init fails

---

lib/tenstorrent/bh_arc/dvfs.c

The 1 ms period should no longer starve CPU time, due to the reduction in TS polling time in #54.

dvfs: restore 1 ms period

---

README.md

Hard-code branch to main for status badges.
Previously, the "default" was used which is to show the most recent status from any branch for a given action, which is not what we're interested in.

readme: hard-code branch to main for status badges

---

boards/tenstorrent/tt_blackhole/spirom_data_tables/GALAXY/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/ORION/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P100/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P100A/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150A/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150C/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300A_L/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300A_R/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300C_L/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300C_R/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300_L/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300_R/fw_table.txt
lib/tenstorrent/bh_arc/spirom_protobufs/fw_table.proto
lib/tenstorrent/bh_arc/vf_curve.c

This updates voltage frequency curve to use voltage and frequency margins from firmware table.
Sets placeholder voltage margin as 50mV for each board type

bh_arc: Implement voltage and margin frequency

---

boards/tenstorrent/tt_blackhole/bootfs/p100-bootfs.yaml
boards/tenstorrent/tt_blackhole/bootfs/p100a-bootfs.yaml
boards/tenstorrent/tt_blackhole/bootfs/p150a-bootfs.yaml
scripts/tt_boot_fs.py

Due to a bug in the update code for BMFW 0.3.1, the erase size is determined by the size of the image rounded to the nearest write size boundary. On the STM32 based BMC, the write size != the erase size, so erases will fail based on this rounding (and updates will not work)
To work around this, pad the BMFW image to a 2048 byte boundary in the tt_boot_fs. This will enable updates to work, at the cost of a bit more flash space used

boards: pad bmfw to nearest 2048 byte boundary

---

boards/tenstorrent/tt_blackhole/tt_blackhole_tt_blackhole_bmc_p300.overlay

Previously the default boot order of the p300 caused chip1 of the board to fail to enumerate when using the recovery image. The reason for this is two fold
1. The recovery image boots both pcie subsystems on the asic 0 and then 1.
2. On the p300 chip0 uses pcie subsystem 0 and chip1 uses pcie subsystem 1.
This meant that the boot would go something like;
1. chip0 boot0 [success]
2. chip0 boot1 [fail]
3. chip1 boot0 [fail]
4. chip1 boot1 [success]
The timing on the boot is so tight that taking 4 steps to fully boot pcie violated pcie bus timing for chip1.
But swapping the chip boot order
1. chip1 boot0 [fail]
2. chip1 boot1 [success]
3. chip0 boot0 [success]
4. chip0 boot1 [fail]
Shortens the total boot time for the pcie subsystems and means we no longer violate pcie bus timing for either …

Swapped chip boot order of p300

---

lib/tenstorrent/bh_arc/regulator.c

Before #49, regulator settings were applying to all PCB types. In #75, @danieldegrasse suspects one of the changes in #49 to be causing p100 CI failures related to PGOOD.
Try to also apply regulator init settings to the p100 PCB Type. This should be ok according to our board team.

regulator: apply init settings to p100

---

app/smc/pytest/e2e_smoke.py
lib/tenstorrent/bh_arc/gddr.c
lib/tenstorrent/bh_arc/gddr.h
lib/tenstorrent/bh_arc/init.c

- CI: Adds check in e2e test that hw_init status is "done" at the end
- GDDR: Adds triggering HW memory test core via MRISC FW at end of init. Will only run if MRISC FW supports this. Version >= 2.7 (not yet released).

Add GDDR HW Memory test

---

.github/workflows/hardware-long.yml

`west init` was failing in CI due to the directory already being configured.
Remove the `.west/` subdirectory before trying to reinitialize.
Testing Done (manually reproduced and remedied issue locally):
```shell
west init -l tt-zephyr-platforms
FATAL ERROR: already initialized in /home/cfriedt/tt-zephyr-platforms-work, aborting.
Note:
In your environment, ZEPHYR_BASE is set to:
/home/cfriedt/tt-zephyr-platforms-work/zephyr
This forces west to search for a workspace there.
Try unsetting ZEPHYR_BASE and re-running this command.
(.venv) cfriedt@yyz-syseng-13:~/tt-zephyr-platforms-work$ rm -Rf .west
(.venv) cfriedt@yyz-syseng-13:~/tt-zephyr-platforms-work$ west init -l tt-zephyr-platforms
=== Initializing from existing manifest repository tt-zephyr-platforms
--- Creating …
```

ci: fix hardware-metal-test failure to run west init

---

lib/tenstorrent/jtag_bootrom/jtag_bootrom.c

If we detect that pcie has already started its boot when we are initializing the bmfw we previously only reset the primary chip. This happens to work on the p1x0 boards because the primary chip is the only asic, but on the p300 with two asics one asic wouldn't recover post tt-flash reset.

Reset both p300 chips if pcie is already booted

---

boards/tenstorrent/tt_blackhole/spirom_data_tables/GALAXY/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/ORION/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P100/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P100A/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150A/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150B/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150C/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300A_L/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300A_R/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300B_L/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300B_R/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300C_L/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300C_R/fw_table.txt

Configure fan_ctrl_en flag in the fw_table to enable/disable fan curve for each board type. Enable for P100A and P150A, but keep disabled for all other boards.

fw_table: enable fan control for P100A and P150A

---

scripts/tt_boot_fs.py
tests/lib/tenstorrent/tt_boot_fs/pytest/test-tt-boot-fs.py

* scripts: tt_boot_fs.py: add `FsEntry.get_descriptor()`
* scripts: tt_boot_fs.py: add `BootFs.check_entry()`
* scripts: tt_boot_fs.py: add failover to `BootFs.entries`
* tests: tt_boot_fs: choose non-corrupt `fw_pack-80.15.0.0.fwbundle`
* tests: tt_boot_fs: correct copy-paste error
* scripts: tt_boot_fs.py: add `ls` subcommand to list fs contents
* tests: tt_boot_fs: add test for `ls` subcommand
Testing Done (aside from added pytest):
```shell
URL="https://github.com/tenstorrent/tt-firmware/raw/7bc0a90226e684962fb039cf26580356d7646574/fw_pack-80.15.0.0.fwbundle"
wget -O /tmp/fw_pack.tar.gz "$URL"
mkdir -p /tmp/fw_pack
tar xpvzf /tmp/fw_pack.tar.gz -C /tmp/fw_pack
```
Copy-paste this into `python3 -i`
```python
import base64
data = None
with open('/tmp/fw_pack/P100-1/image.bin', 'r') as …
```

scripts: tt_boot_fs.py: add ls subcommand to list boot fs contents

---

app/smc/pytest/e2e_smoke.py
app/smc/pytest/pytest.ini
app/smc/sample.yaml
cmake/bundle_version.cmake
lib/tenstorrent/bh_arc/CMakeLists.txt
scripts/encode_spirom_bins.py
scripts/manual-release.sh

Change the format of the bundle version to use: major.minor.patch.tweak from the VERSION file. Compile this version number into the fw_table and the manifest.json of the update.fwbundle. Also update manual-release.sh to name the file according to the new scheme.
Add an e2e test to check that the bundle version matches the VERSION file in the repo.
Output of `manual-release.sh`, `tt-flash`, and `tt-smi`:
```
[2254] afong:yyz-syseng-16 /localdev/afong/work/zephyrproject/tt-zephyr-platforms.git > ./scripts/manual-release.sh 
Created TEMP_DIR
Building release 80.16.111.111-rc1 / pack 80.16.111.111
Building tt_blackhole@p100/tt_blackhole/smc
Building tt_blackhole@p100a/tt_blackhole/smc
Building tt_blackhole@p150a/tt_blackhole/smc
Building tt_blackhole@p150b/tt_blackhole/smc
Building …
```

version: report bundle version in telemetry

---

app/bmc/prj.conf
app/smc/prj.conf
app/smc/vuart.conf
lib/tenstorrent/banner/CMakeLists.txt
lib/tenstorrent/banner/Kconfig
lib/tenstorrent/banner/tt_banner.c

Print the git revision in the format
```
*** TT_GIT_VERSION b7d6567 ***
```
when `CONFIG_TT_BOOT_BANNER_GIT_VERSION` is enabled.

app: bmc + smc: print the tenstorrent git revision along with the boot banner

---

.github/workflows/hardware-long.yml
.github/workflows/hardware-smoke.yml

If a customer buys a Tenstorrent card, they should be able to set up their own CI infrastructure.
Approval for workflow runs is already restricted via settings.
```
Settings -> Actions -> General ->
Approval for running fork pull requests... from contributors
-> Require approval for all external contributors
```
Secrets are per-organization / repo

ci: allow forks to run their own CI

---

lib/tenstorrent/banner/CMakeLists.txt

Use APPLICATION_SOURCE_DIR for the `git describe` step- otherwise, git describe will fail when building the application from outside of the tt-zephyr-platforms repo

lib: tenstorrent: banner: use APPLICATION_SOURCE_DIR for git describe

---

.github/workflows/hardware-long.yml

Remove tt-metal tests that are not part of v55 of metal to which hardware long tests are currently pinned.

Remove tt-metal tests that are not part of v55 of metal to which hardware long tests are currently pinned.

---

lib/tenstorrent/bh_arc/pcie.c
lib/tenstorrent/bh_arc/pciesd.h

Added a few comments
- function declarations that should not be changed as pre-compiled library uses them
- highlights functions implemented in pre-compiled library
https://tenstorrent.atlassian.net/browse/SYS-1381

pcie: improve mantainability

---

app/bmc/prj.conf
app/smc/prj.conf
lib/tenstorrent/banner/CMakeLists.txt
lib/tenstorrent/banner/Kconfig
lib/tenstorrent/banner/tt_banner.c

Add print of Zephyr SDK revision during boot. This will enable truly reproducible builds, since we will be able to use the same toolchain and SHA.

lib: tenstorrent: banner: add print of Zephyr SDK revision

---

.github/workflows/build-fw.yml
.github/workflows/build-native.yml
.github/workflows/copyright-check.yml
.github/workflows/hardware-long.yml
.github/workflows/hardware-smoke.yml
.github/workflows/license-check.yml
.github/workflows/release.yml
.github/workflows/run-unit-tests.yml

Checkout ${{ github.ref }} instead of the default SHA for the github checkout event. This resolves an issue where restarting CI on a failed job would not merge the PR branch with the latest main, so CI fixes from external PRs would not be picked up.

ci: workflows: checkout github.ref instead of default SHA

---

lib/tenstorrent/bh_arc/regulator.c

Should overwrite the entire 11 bits of mantissa field for IOUT_CAL_GAIN and IOUT_CAL_OFFSET, exponent fields are not overwritable.
https://tenstorrent.atlassian.net/browse/SYS-1430

i2c: adjust mask for iout cal

---

boards/tenstorrent/tt_blackhole/bootfs/p150b-bootfs.yaml
boards/tenstorrent/tt_blackhole/bootfs/p150c-bootfs.yaml
boards/tenstorrent/tt_blackhole/bootfs/p300a-left-bootfs.yaml
boards/tenstorrent/tt_blackhole/bootfs/p300b-left-bootfs.yaml
boards/tenstorrent/tt_blackhole/bootfs/p300c-left-bootfs.yaml

Added bmfw padding to all board types; required to make sure the SPI driver will be able to read the binaries in order to self-update.

Ensure that the bmfw is padded to 0xb000 for all boards

---

lib/tenstorrent/bh_arc/dw_apb_i2c.c

At the final step of the I2C recovery sequence, we need to release the SDA line to allow it to be pulled high. Fix the GPIO TRIEN bitmask we write so that this will actually occur.

bh_arc: fix I2C recovery sequence

---

.github/workflows/hardware-smoke.yml
.github/workflows/prepare-hardware/action.yml

Flash a stable copy of BMFW and CMFW prior to HW smoke and e2e tests, so any bad state from a prior PR run is fixed.

ci: flash a stable copy of BMFW and CMFW prior to HW CI runs

---

boards/tenstorrent/tt_blackhole/spirom_data_tables/GALAXY/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/ORION/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P100/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P100A/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150A/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150B/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150C/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300A_L/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300A_R/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300B_L/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300B_R/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300C_L/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300C_R/fw_table.txt
lib/tenstorrent/bh_arc/aiclk_ppm.h
lib/tenstorrent/bh_arc/fan_ctrl.c
lib/tenstorrent/bh_arc/spirom_protobufs/fw_table.proto
lib/tenstorrent/bh_arc/telemetry.c
lib/tenstorrent/bh_arc/telemetry.h
lib/tenstorrent/bh_arc/throttler.c

Add current maximum GDDR temperature to the telemetry table. Add a throttler based on GDDR temperature. Add GDDR thermal throttler limit to FW table.

tenstorrent: bh_arc: add gddr throttler

---

.github/workflows/hardware-smoke.yml

Increase stable firmware revision flashed in CI. Based on RTT logs, it appears the CI instability may be due to flashing a stable CMFW that still has the I2C hang issue- if so, upgrading to fw bundle 80.17.0.0 should resolve this

ci: increase stable firmware revision

---

.github/workflows/build-fw.yml
.github/workflows/build-native.yml
.github/workflows/compliance.yml
.github/workflows/copyright-check.yml
.github/workflows/hardware-long.yml
.github/workflows/hardware-smoke.yml
.github/workflows/license-check.yml
.github/workflows/release.yml
.github/workflows/run-unit-tests.yml
scripts/build-combined-fwbundle.sh

* scripts: build-combined-fwbundle: use pre-built per-board fwbundles
* ci: release: ensure publish-release depends on build-release
* ci: release: simplify firmware bundle logic
* ci: build-fw: run build-combined-firmware in CI
* ci: release: add combined firmware bundle to release artifacts
* ci: release: artifacts for p150b p150c p300a p300b and p300c
* ci: cancel previous workflow runs on force push
Testing Done (for `./scripts/build-combined-fwbundle.sh`):
```shell
BUNDLE_TEMP_PREFIX="$PWD/build-" ./scripts/build-combined-fwbundle.sh 
Using existing BUNDLE_TEMP_PREFIX: /Users/cfriedt/tt-zephyr-platforms-work/tt-zephyr-platforms.git/build-
Building release 18.1.99 / pack 18.1.99.0
Using pre-built build-p100/update.fwbundle
Using pre-built build-p100a/update.fwbundle
Using pre-built …
```

ci: release: artifacts for p150b p150c p300a p300b and p300c

---

.github/workflows/hardware-smoke.yml

p100a machines need manual recovery almost constantly. p100 seems fine. 
It's a massive waste of developer time and is blocking CI, so just disable p100a until we can reliably run tests on that platform as part of the regular test sequence (which I hope is ASAP).
Case in point:
* https://github.com/tenstorrent/tt-zephyr-platforms/pull/160
* the PR above simply adds `tt-smi` to `scripts/requirements.txt`
* there should be zero reason for CI failing on p100a hardware tests
Likely the same problem will plague p150a, p150b, p150c, p300a, p300b, and p300c systems, so it needs to be done right.
Temporary workaround for #162, but that will need a fix ASAP.

ci: temporarily disable p100a hw tests until it runs reliably

---

.github/workflows/prepare-zephyr/action.yml
scripts/requirements.txt

Ensure that `tt-smi` is installed (this is typically done via `west packages pip --install`).
Python packages are installed as part of `zephyrproject-rtos/action-zephyr-setup`, so remove the additional manual `pip` invocation.
https://github.com/zephyrproject-rtos/action-zephyr-setup/blob/db1412e2ab8e2c07b1f866541e66aec41b20d244/action.yml#L141

scripts: requirements: add tt-smi to required python packages

---

lib/tenstorrent/bh_arc/telemetry.c

Remove static_telemetry_init for BMFW version as it races the bmfw BMFW version update.

Do not initialize bmfw_version in telemetry.c

---

scripts/bmc-reset.py
scripts/find_zephyr_sdk.cmake

Add support in the bmc-reset script for waiting for the SMC boot, and autodetect paths like the Zephyr SDK where possible.
~Use this script within CI, so that we can have more reliable BMC flashing~

scripts: bmc-reset: add support for waiting for SMC boot, autodetect paths

---

.github/workflows/build-fw.yml

This enables the PCIe Virtual UART by default in the build-fw workflow only so that users can use `tt-console`.
This is a temporary solution until #72 is able to pass tests in CI.

ci: build-fw: enable virtual uart by default for published binaries

---

.github/workflows/hardware-long.yml

To update the metal version to the latest version, we need to change how we install dependencies in the workflows.
- Broke down the workflow into two jobs
- Got rid of manual installation of metal and started using a metal container 
- Upgraded metal to ~v0.56.0~ ~almeet's branch `abhullar/bh-virtual` ~ now on Metal main.
TODO:

Use Metal Container for running Hardware Long tests & Add required Metal tests

---

scripts/build-combined-fwbundle.sh

Enable the virtual uart by default in `scripts/build-combined-fwbundle.sh` as well.
This is a follow-up PR to #169

scripts: build-combined-firmware-bundle: use virtual uart

---

.github/workflows/hardware-long.yml

UMD reference was broken yesterday due to removal of GS headers.
This PR was merged and fixed UMD - https://github.com/tenstorrent/tt-metal/pull/21471

Fix metal reference

---

lib/tenstorrent/bh_arc/telemetry.c
lib/tenstorrent/bh_arc/telemetry.h
lib/tenstorrent/bh_arc/throttler.c

Add BOARD_PWR_LIMIT telemetry field.
Whenever board power limit is received from BMC FW, update it in the telemetry table.

bh_arc: add board power limit to telemetry table

---

.github/workflows/release.yml

Enable the release workflow for release candidates. This will enable artifact generation for the usual artifacts with fewer manual steps.

ci: release: enable release workflow even for rcs

---

.github/workflows/hardware-long.yml
.github/workflows/hardware-smoke.yml
.github/workflows/prepare-zephyr/action.yml
app/bmc/sample.yaml
app/smc/Kconfig.sysbuild
boards/tenstorrent/tt_blackhole/board.yml
boards/tenstorrent/tt_blackhole/revision.cmake
boards/tenstorrent/tt_blackhole/tt_blackhole_tt_blackhole_bmc_p150a.yaml

Use generic tags for blackhole runners, as we now have two P100a runners online. Enable P150 runner in CI.

ci: use generic tags for blackhole, enable P150

---

lib/tenstorrent/bh_arc/dw_apb_i2c.c

Add the following improvements to the I2C recovery function used when the I2C bus sticks:
- forcibly hold SCL low for 100ms, to induce a reset for PMBUS/SMBUS devices
This PR also adds a `reset-hammer` test, which runs as part of the long hardware testsuite. This test takes roughly 75 minutes to complete, and resets the SMC 1000 times, each time verifying there is no I2C hang. Each reset is performed twice in quick succession, because in my testing this had the best chance of reproducing I2C issues (presumably because regulator init occurs during early boot)
A link to a run of this test within the PR can be seen here, before I moved it to the nightly tests: [tenstorrent/tt-zephyr-platforms/actions/runs/14767700634/job/41462250566?pr=168](https://github.com/tenstorrent/tt-zephyr-platforms/a …

lib: tenstorrent: improve I2C recovery function

---

.github/workflows/hardware-long.yml
lib/tenstorrent/bh_arc/dw_apb_i2c.c
lib/tenstorrent/bh_arc/dw_apb_i2c.h
lib/tenstorrent/bh_arc/regulator.c
scripts/run-reset-hammer.sh

Add a reset hammer test, intended to be run nightly. This test will reset the SMC repeatedly, and verify that I2C hangs do not occur when the SMC crashes (or is reset) during early init.
This PR also includes additional I2C recovery fixes, and should not be merged until the reset hammer test is passing at 1000 iterations on P100/P100a/P150a

lib: tenstorrent: continued elimination of I2C gremlins

---

MAINTAINERS.yml

Add a release notes maintainer to the maintainers file.
This file intentionally uses the same structure as that from the Zephyr Project. It is intended to be used programmatically to associate areas of code (C, devicetree, documentation, etc) to various individuals within Tenstorrent's firmware organization.
Additional areas and maintainers should be added soon.
Please see the upstream maintainers file for more info:
https://github.com/zephyrproject-rtos/zephyr/tree/main/MAINTAINERS.yml
* also added required entries for entries in `west.yml`, otherwise there were compliance errors

maintainers: add release notes maintainer to the maintainers file

---

MAINTAINERS.yml

Add Daniel DeGrasse and Chris Friedt as CI maintainers.
Not sure if I care enough to add a [maintainers file maintainer](https://github.com/zephyrproject-rtos/zephyr/blob/64fe434297c6c7e6cfb8fcc5c49c9b1f78114569/MAINTAINERS.yml#L2700)

maintainers: add danieldegrasse and cfriedt as ci maintainers

---

doc/release/migration-guide-18.2.0.md
doc/release/release-notes-18.2.0.md

Add release notes and migration guide for version 18.2.0 of tt-zephyr-platforms.

doc: release: v18.2.0: add release notes and migration guide.

---

.github/workflows/release.yml

The "Package firmware artifacts" step was failing in the release workflow because it could not find a path.
```shell
cp: cannot stat 'build-*/update.fwbundle': No such file or directory
```
The correct commands to run in the loop would be
```shell
mv firmware-$REV $REV
mv $REV/update.fwbundle $REV.fwbundle
```
Made two drive-by optimizations:
1. skip re-running `prepare-zephyr`
* reuse pre-built artifacts entirely
* makes this workflow very fast
2. moved SPDX to a separate job, `build-spdx`
* otherwise, it was pulling in sources from modules, which is [not what Zephyr does](https://github.com/zephyrproject-rtos/zephyr/blob/2707fa2fcaf83cf21ba7f493d339b1783463f2c8/.github/workflows/release.yml#L13)
* i.e. our SPDX will only include code from `tt-zephyr-platforms` and nothing from modules …

ci: release: correct path for package firmware artifacts

---

doc/release/release-notes-18.2.0.md

Add a release note stating that the PCIe Virtual UART is enabled by default for Blackhole firmware bundles.
Use the provided `tt-console` app to view `printk()` and `LOG_*()` messages from firmware on Linux hosts.
```
cd tt-zephyr-platforms
gcc -Iinclude -O0 -g -Wall -Wextra -Werror -std=gnu11 -o tt-console \
scripts/tt-console/console.c
```

doc: release: v18.2.0: note that virtual uart is enabled by default

---

.github/workflows/hardware-long.yml

Switch to Metal Upstream Container:
https://github.com/tenstorrent/tt-metal/pkgs/container/tt-metal%2Fupstream-tests-bh
The metal workflow to build these containers is here:
https://github.com/tenstorrent/tt-metal/actions/workflows/upstream-tests.yaml
This metal workflow can be used to create a test container from any commit and meets the requirements from Chris and Daniel about being able to test any metal commit against any commit of firmware.

Use Metal Upstream Container in Hardware Long workflow

---

.github/workflows/hardware-smoke.yml

Twister pytest outputs are written to `twister_harness.log`, and are more readable without debug logging enabled. Turn off debug logging since we can still get useful output from those files.

ci: drop debug logging from twister runs

---

app/bmc/src/main.c

Instead of detecting max board power every time a chip is reset, detect it once at the beginning of the app.

app: bmc: move board power limit detection to BMC app init

---

app/smc/pytest/e2e_smoke.py

In some cases, no card is on the PCIe bus at the start of the test. Still support rescanning this case

app: pytest: e2e_smoke: support rescan if no card is on bus

---

.github/workflows/prepare-zephyr/action.yml
zephyr/module.yml

Add `package-managers` and `pip` to `zephyr/module.yml`, which ensures that `west packages pip --install` picks up pypi packages for our module.
Testing Done:
```shell
% west packages pip
-r /Users/cfriedt/tt-zephyr-platforms-work/zephyr/scripts/requirements.txt
-r /Users/cfriedt/tt-zephyr-platforms-work/tt-zephyr-platforms.git/scripts/requirements.txt
-r /Users/cfriedt/tt-zephyr-platforms-work/modules/lib/nanopb/extra/requirements.txt
-r /Users/cfriedt/tt-zephyr-platforms-work/bootloader/mcuboot/zephyr/requirements.txt
```
See also
https://docs.zephyrproject.org/latest/develop/modules.html#python-pip

zephyr: module: add package-managers so that pip installs automatically

---

.github/workflows/prepare-zephyr/action.yml
scripts/requirements.txt

`tt-smi` and `tt-flash` both depend on different (fixed) versions of `pyluwen` (they should probably use `>=`). In any case, the pip `scripts/requirements.txt` file was failing to get installed and as a result, `protoc` was failing.
Resolve the dependencies for now.
This was causing multiple PRs to fail.

ci: prepare-zephyr: resolve tt-smi tt-flash version conflict

---

boards/tenstorrent/tt_blackhole/Kconfig.defconfig

Automatically select LOG_BACKEND_RTT and LOG_MODE_DEFERRED for the DMC.
Also select `LOG_BACKEND_RTT_MODE_DROP` since otherwise, the system could lock up if the logging thread becomes blocked on available buffer space (which is an eventuality if there are no processes actively reading from it).
Due to a quirk in ZTest, there is a possibility that the core may halt before all log messages are retrieved via RTT console.
However, since ZTest waits until the log buffer is flushed (by default), then if we enable the RTT log backend, we can ensure that logging is not stopped prematurely and that twister is able to capture all of the log output.
https://github.com/zephyrproject-rtos/zephyr/blob/e1f4181c29960e5924779d64ad6ac7c8d6ad0259/subsys/testsuite/ztest/src/ztest.c#L723
Fixes #219
Additional …

boards: tt_blackhole: dmc: select rtt backend and deferred log mode

---

boards/tenstorrent/tt_blackhole/p300_tt_blackhole_dmc.dts

Blackhole boards all have external resisters pulling-up SCL, SDA, and interrupt lines up to 1.8V.
Delete the devicetree property so that only one resister is pulling- up, and to minimize potential electrical issues.

boards: tt_blackhole: dmc: delete bias-pull-up property of i2c1

---

.github/workflows/hardware-smoke.yml

While looking at test results for #164, I realized we aren't uploading the `twister_harness.log` file where pytest results are stored.
This PR fixes that issue, as well as a few other improvements:
- enable uploading hidden files so that the `.config` file gets uploaded
- combine the e2e-flash and e2e-smoke uploads, since we are going to run some tests exclusively within the `e2e-flash` run

ci: fixes for build artifact uploads

---

app/smc/pytest/e2e_smoke.py

Add a test to hardware-smoke that performs a tt-smi reset and checks for successful reset and chip access

ci: Add tt-smi -r smoke test

---

app/dmc/src/main.c
app/smc/src/main.c
include/tenstorrent/bh_chip.h
lib/tenstorrent/bh_arc/cm2dm_msg.c
lib/tenstorrent/bh_arc/cm2dm_msg.h
lib/tenstorrent/jtag_bootrom/jtag_bootrom.c

BMC FW attempts to send board power limit before SMC FW is guaranteed to be initialized. This results in unintentional throttling down to the default board power limit of 150W.
Add a cm2bm message to notify BMC FW when it's okay to start sending data.

smbus messaging: notify BMC FW when SMC FW is ready to receive msg

---

app/dmc/src/main.c
boards/tenstorrent/tt_blackhole/spirom_data_tables/P100A/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150A/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150B/fw_table.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150C/fw_table.txt
lib/tenstorrent/bh_arc/spirom_protobufs/fw_table.proto
lib/tenstorrent/bh_arc/throttler.c

We have been getting the board power limit from a strapping GPIO connected to the DMC on p100a and p150a/b/c. However on the boards that we've checked, this strap does not follow our product definition.
Use a SPI FW table parameter to get this limit instead of the strapping GPIO. Update the limits to the product definition values.
Internal ticket: https://tenstorrent.atlassian.net/browse/SYS-1511

Get board power limit from SPI FW Table

---

scripts/pre-push.sh

Ruff check should not be excluded from git hook, as it is run by the CI checker github

scripts: pre-push: add ruff to check list

---

scripts/pcie_utils.py

Commit d33106d (app: pytest: e2e_smoke: support rescan if no card is on bus) added this behavior to the e2e smoke test, but commit d1ea6e1 (boards: tt_blackhole: rename bmc to dmc to avoid confusion) did not port the behavior into the new pcie_utils.py script. Reintroduce it.

scripts: pcie_utils.py: rescan even if no card is on bus

---

.github/workflows/hardware-smoke.yml

Change workflows to use hw-map.yml instead of hw-map-dmc.yml after renaming bmc to dmc.
Additionally:
* ci: hardware-smoke: mount /opt/tenstorrent volume once
* ci: hardware-smoke: only use openocd-rtt for arc

ci: switch back to hw-map.yml after dmc rename

---

doc/release/migration-guide-18.3.0.md

Correct the version number in the migration guide from v18.2.0 to v18.3.0

doc: release: v18.3.0: correct version in migration guide

---

doc/release/migration-guide-18.3.0.md
scripts/build-combined-fwbundle.sh

Use the semantic version in the filename of the firmware bundle rather than the quad-dotted versioning scheme historically used.
Going forward, release candidate firmware packs will have names like `fw_pack-18.3.0-rc1.fwbundle` rather than `fw_pack-18.3.0.1.fwbundle`, and
final releases will have names like `fw_pack-18.3.0.fwbundle` rather than
`fw_pack-18.3.0.0.fwbundle`.
Fixes #228
Testing done (manual, but also from the "build combined fwbundle" job in this PR):
```shell
Creating fw_pack-18.3.0-rc1.fwbundle
Wrote fwbundle to fw_pack-18.3.0-rc1.fwbundle
```

scripts: build-combined-fwbundle: use semantic version in filename

---

doc/release/release-process.md

Document manual steps required to create a `tt-firmware` release from the
automated release from `tt-zephyr-platforms`.
In the future, it might be better to automate this process using
GitHub actions, or simply sunset the old `tt-firmware` repository, and
rename `tt-zephyr-platforms` to `tt-firmware`. Making firmware releases in
two locations seems a bit redundant.

doc: release: add manual steps for creating a tt-firmware release

---

doc/release/migration-guide-18.3.0.md

Add a note to the migration guide about renaming the board management controller to device management controller, to avoid confusion with the baseboard management controller from the IPMI specification.

doc: release: v18.3.0: note bmc dmc rename in migration guide

---

doc/release/migration-guide-18.3.0.md
doc/release/release-notes-18.3.0.md

Update release notes and migration guide to note usage of input power instead of input current.

doc: release: v18.3.0: note usage of input power instead of current

---

app/dmc/Kconfig
app/dmc/sample.yaml
app/dmc/src/main.c
app/smc/pytest/e2e_smoke.py
include/tenstorrent/bh_arc.h
lib/tenstorrent/bh_arc/cm2dm_msg.c
lib/tenstorrent/bh_arc/cm2dm_msg.h
lib/tenstorrent/bh_arc/smbus_target.c
lib/tenstorrent/bh_arc/telemetry.c
lib/tenstorrent/bh_arc/telemetry.h
lib/tenstorrent/bh_chip/bh_arc.c
zephyr/patches.yml
zephyr/patches/zephyr/check-compliance.patch

This PR enables reading telemetry tags via SMBUS, using the following scheme:
| Register       | Address | Width   | Usage                                                                                                                             |
|----------------|---------|---------|-----------------------------------------------------------------------------------------------------------------------------------|
| TELEMETRY_TAG  | 0x26    | 8 bits  | Write only. Write with telemetry tag value to select which telemetry field will be read when reading from TELEMETRY_DATA register |
| TELEMETRY_DATA | 0x27    | 32 bits | Read only. Read to get the latest telemetry data for the tag programmed to TELEMETRY_TAG register                                 |
The `TELEMETRY_TAG` register is …

lib: tenstorrent: support reading telemetry tags via SMBUS

---

app/dmc/src/main.c
include/tenstorrent/bh_arc.h
include/tenstorrent/tt_smbus_regs.h
lib/tenstorrent/bh_arc/cm2dm_msg.c
lib/tenstorrent/bh_arc/cm2dm_msg.h
lib/tenstorrent/bh_arc/smbus_target.c
lib/tenstorrent/bh_chip/bh_chip.c

Rather than using magic numbers for SMBUS registers within the DMFW and
CMFW, define all SMBUS registers in a header file, and reuse this header
file in the DMFW and CMFW to avoid potential mismatches.
Additionally, remove duplicated cm2dm messaging structure definitions, and use the ones provided by the DMFW in both firmwares.
This PR is exclusively code cleanup, it has no functional changes

lib: tenstorrent: add definitions for SMBUS registers, remove cm2dm duplication

---

lib/tenstorrent/bh_arc/functional_efuse.h
lib/tenstorrent/bh_arc/telemetry.c
lib/tenstorrent/bh_arc/telemetry.h

Each BH ASIC is fused with a unique 64 bit ASIC ID during testing. Add two new fields to telemetry to expose this, ASIC_ID_HIGH and ASIC_ID_LOW.
Remove ASIC_ID from telemetry table, which was added when a 32 bit value was expected.

bh_arc: expose fused ASIC ID in telemetry

---

zephyr/module.yml

firmware blob sha should have been updated in
f5011bda57940fb2513804282eec3f389ed99926. Update it here so CI will pass.

module: update sha for wormhole fw blob

---

.github/workflows/release.yml

Release job needs write permissions on the contents of the repository in order to create a draft release, so add this setting to the workflow.
here is a job failing based on the v18.4.0-rc1 tag: [danieldegrasse/tt-zephyr-platforms/actions/runs/15338904861/job/43162145000](https://github.com/danieldegrasse/tt-zephyr-platforms/actions/runs/15338904861/job/43162145000). I created a 18.4.0-rc2 tag on my fork with the commit in that PR, and the release action succeeds there: [danieldegrasse/tt-zephyr-platforms/actions/runs/15339297827](https://github.com/danieldegrasse/tt-zephyr-platforms/actions/runs/15339297827)

ci: workflows: add permissions to release job

---

lib/tenstorrent/bh_arc/gpio.h
lib/tenstorrent/bh_arc/pcie.c

drive PERST of CEM1 slot when operating in RC mode

pcie: enable CEM1 in RC mode

---

boards/tenstorrent/tt_blackhole/spirom_data_tables/GALAXY/read_only.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/ORION/read_only.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P100/read_only.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P100A/read_only.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150A/read_only.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150B/read_only.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P150C/read_only.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300A_L/read_only.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300A_R/read_only.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300B_L/read_only.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300B_R/read_only.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300C_L/read_only.txt
boards/tenstorrent/tt_blackhole/spirom_data_tables/P300C_R/read_only.txt
scripts/encode_spirom_bins.py

Encode a default board ID into the output flash image. This won't be present in the generated tt_boot_fs binary, but can be manually included with tt_boot_fs.py. This is useful for board recovery cases where the board ID has been erased.

boards: tenstorrent: encode a default board ID into flash images

---

.github/workflows/release.yml

Automatically add release notes to draft release.
Testing Done:
final:
https://github.com/cfriedt/tt-zephyr-platforms/actions/runs/15508836931
https://github.com/cfriedt/tt-zephyr-platforms/releases/tag/v0.0.0
rc:
https://github.com/cfriedt/tt-zephyr-platforms/actions/runs/15512425139
https://github.com/cfriedt/tt-zephyr-platforms/releases/tag/v0.0.0-rc1

ci: release: automatically add release notes to draft release

---

lib/tenstorrent/bh_arc/cm2dm_msg.c
lib/tenstorrent/jtag_bootrom/jtag_bootrom.c

Prevent invalid overwrite of dmc init time by clearing perst seen after recording dm init done.
tt-smi reset does not reset DMC. Since perst seen is not cleared, it causes invalid overwrite of dmc init duration.
In cases where DMC get reset, dmc will just write 0 as init duration.

dmc: prevent invalid overwrite of dmc init time

---

README.md
zephyr/module.yml

By filling-in the 'name' field of our module as `tt-zephyr-platforms`, it will be checked-out to `tt-zephyr-platforms` instead of `tt-zephyt-platforms.git`, and we can use the variable `ZEPHYR_TT_ZEPHYR_PLATFORMS_MODULE_DIR` in CMake.
https://docs.zephyrproject.org/latest/develop/modules.html#module-name

zephyr: use a dedicated name for our module

---

.github/workflows/verify-blob.yml
scripts/verify_blob.py

Merging outdated blob sha256sum in module.yml can break CI.
Implemented blob sha256sum checks.
sample output when mismatched blob is detected
```
Blob tt_blackhole_gddr_init.bin has changed. Expected SHA256: df1ceefa477e5d8fbb02f37b1e5e0a0c7aabb875669167e6db2f7ce7cb9e6325, but got 97372fed110dd3fe8d3feba4260e6f48db8e30b0bf08ced31a0628b0ba4ed7e8.
Error: Process completed with exit code 1.
```

scripts:verify-blob: add blob sha256sum checks

---

README.md

Drop the .git suffix of the module repo so that when it is checked-out it is checked-out to tt-zephyr-platforms-work/tt-zephyr-platforms instead of tt-zephyr-platforms-work/tt-zephyr-platforms.git .
Testing done:
```shell
$ MODULE=tt-zephyr-platforms
$ west init -m https://github.com/tenstorrent/$MODULE /tmp/$MODULE-work
$ cd /tmp/$MODULE-work
$ ls
tt-zephyr-platforms
```

readme: drop .git suffix of module repo

---

.github/workflows/prepare-zephyr/action.yml

Remove stm32 blobs that could potentially cause sha256sum mismatch errors in `west blobs fetch` if a runner work area is unclean.
This should mitigate CI errors such as the one below:
```shell
Fetching blob hal_stm32: /home/runner/work/tt-zephyr-platforms/tt-zephyr-platforms/modules/hal/stm32/zephyr/blobs/stm32wba/lib/LinkLayer_BLE_Full_lib.a
ERROR: The checksum of the downloaded file does not match that
Fetching blob hal_stm32: /home/runner/work/tt-zephyr-platforms/tt-zephyr-platforms/modules/hal/stm32/zephyr/blobs/stm32wba/lib/stm32wba_ble_stack_llo.a
in the blob metadata:
- if it is not certain that the download was successful,
try running 'west blobs fetch hal_stm32'
to re-download the file
- if the error persists, please consider contacting
the maintainers of the module so that they …
```

ci: remove stm32 blob directory in 'remove existing data' step

---

boards/tenstorrent/tt_blackhole/tt_blackhole_tt_blackhole_smc.dts
dts/arc/tenstorrent/tt_blackhole_smc.dtsi
dts/bindings/debug/tenstorrent,bh-chip-debug-trace.yaml
dts/bindings/ethernet/tenstorrent,bh-eth.yaml
dts/bindings/memory-controllers/tenstorrent,bh-memc.yaml
dts/bindings/misc/tenstorrent,noc.yaml
dts/bindings/regulator/maxim,max20730.yaml
dts/bindings/regulator/maxim,max20816.yaml
dts/bindings/regulator/mps,mpm3695.yaml

Add skeleton DT bindings and nodes for a number of missing devices in the SMC SoC and board-level devicetrees.
The bindings and node properties should be elaborated when the drivers are implemented.

soc + board: tt_blackhole: add skeleton dt bindings and nodes for missing devices

---

doc/release/release-notes-18.6.0.md
lib/tenstorrent/bh_arc/pvt.c
lib/tenstorrent/bh_arc/pvt.h

cmfw pulls on sdif read for PD and TS reading, if sdif done is not set, then cmfw could hang pulling. Use 10ms as timeout, as TS takes ~1ms for each sample, and PD takes ~0.1ms for each sample.

pvt: implement sdif done timeout

---

.github/workflows/cleanup-branches.yml

Add write permissions to the workflow so it can properly delete
branches.
Remove the GitHub token as it is not needed.
Fixes: SYS-1660

.github: workflows: cleanup-branches.yml: add delete permissions

---

app/smc/pytest/e2e_smoke.py

Increase delay before checking if SMC has communication with DMC, to improve reliability of the arc watchdog test

app: smc: test_arc_watchdog: increase delay before polling DMC

---

.github/workflows/assigner.yml
MAINTAINERS.yml
scripts/set_assignees.py

Within the `MAINTAINERS.yml` file, there are or will be several areas of interest to Tenstorrent in terms of code ownership, delegation of responsibility for improvement and bugfixes, testing, and so on.
Add each of those areas with a "Maintainer needed!" comment.
This coincides with a salient point brought up at the recent SysEng F2F meeting where we established that code-ownership is critical to platform stability and management of technical debt.
Being a maintainer or collaborator is a merit-based role. Before anyone is added to the `MAINTAINERS.yml` file, they must demonstrate that they have made contributions to the area, understand what it takes to make improvements in the area, and commit to responding to issues in a timely manner.
The `MAINTAINERS.yml` file is also used by the …

maintainers: add areas of interest for tenstorrent

---

zephyr/patches.yml

Add merge PRs for patches we can upstream, to improve tracking prior to 4.2 release.

patches: record merge PRs for upstreamable patches

---

zephyr/patches.yml

I guess if there is a merge-date, then merge-status is implicitly true.
In any case, the merge-date field is helpful too.

patches: add merge details like merge-date and merge-status

---

zephyr/patches.yml
zephyr/patches/zephyr/i2c-dw-bus-recovery.patch

Backport the changes made in upstream PR 89386 to facilitate i2c bus recovery in the designware i2c driver.

zephyr: patches: backport pr 89386 for dw i2c bus recovery

---

zephyr/patches.yml

Adds link to upstream PR, which was rejected since the test suite was originally intended to just be used to verify PWM controller device/API and not run on actual hardware

zephyr: patches: update upstreamable status for pwm_api test patch

---

.github/workflows/release.yml

Populate boards from json in the prepare-release job and output the values so that they are usable in the "package firmware artifacts" job.
This is specifically to address this issue in the release workflow.
https://github.com/tenstorrent/tt-zephyr-platforms/actions/runs/16061958246/job/45329765672

ci: release: populate boards in prepare-release job

---

.github/workflows/release.yml

Quote output of jq so that the output does not spill over multiple lines.
This addresses the error linked below in the release workflow.
https://github.com/tenstorrent/tt-zephyr-platforms/actions/runs/16062574984/job/45331264386

ci: release: quote output of jq

---

lib/tenstorrent/bh_arc/pvt.c

Alarm B lines of the thermal sensors are ORed together (and also with CAT sensor) and output on GPIO31 for board shutdown. Increase the Alarm B point to 109C based on Tj,shutdown=110C and thermal sensor +-1C accuracy (when calibrated).

Raise thermal sensor shutdown to 109C, based on Tj,shutdown

---

.github/workflows/hardware-long.yml
.github/workflows/hardware-smoke.yml
scripts/requirements.txt

Smoke tests and soak tests were both failing on p150a during the "Flash the firmware" step with the error that there were flash region mismatches. The workflows use version 3.3.3 .
http://bit.ly/45WZ7Rs
http://bit.ly/46eEWyL
However, manual repro on the same p150a machine using version 3.3.5 does not produce any flash region mismatches.
https://pastebin.com/vknhTuZD
Bump the version of the tt-flash to v3.3.5 and bump the version of tt-smi to v3.0.23.

ci: bump tt-flash rev to 3.3.5, tt-smi rev to 3.0.23

---

.github/workflows/hardware-smoke.yml

Upload device log from twister runs, so we can debug why flashing steps failed

ci: workflows: upload device log

---

.github/workflows/stale_issue.yml

Duplicate the upstream stale issue workflow to clean up inactive pull requests and issues.

ci: add a stale bot to clean up inactive PRs and issues

---

scripts/build-combined-fwbundle.sh

There was a lingering TODO comment that said to load board revisions from a yaml file. We do that now (well, a JSON file technically), so can remove the comment.

scripts: build-combined-fwbundle: remove stale comment

---

scripts/pre-push.sh

CI check in tt-zephyr-platforms excludes a different set of checks than the pre push hook did. Update the hook to use the same set of checks.

scripts: pre-push: update to align with CI check command

---

lib/tenstorrent/bh_arc/Kconfig
lib/tenstorrent/bh_arc/init_common.h

We had some difficulty building our application with debug information before because the linked binary would not fit into memory reserved for cmfw.
Reduce the large scratchpad size down from 64 kB to 36kB, which is just larger than the size of ERISC firmware. The size can be further reduced by adjusting the firmware loading algorithms to be flash-aware. If using malloc is a possibility then the buffers can be freed when they are no longer required, which would allow for additional runtime memory usage.
Technically, I think we should also be able to extend the boundary within CSM (SRAM) where CMFW may be loaded, but if we can get away with using a smaller static buffer and still meet the same performance and functional requirements, we might as well do that too.

lib: bh_arc: reduce scratchpad size down from 64 kB to 36kB

---

drivers/serial/uart_tt_virt.c
scripts/tt-console/console.c

Fix a few issues prevent vuart input from functioning correctly. With these changes the shell works on the SMC:
Note that the SMC ram size (in the LD file) needs to be increased to get the shell to fit without overflowing the SRAM region, but it does work

scripts: tt-console: properly support vuart input

---

west.yml
zephyr/patches.yml
zephyr/patches/zephyr/pr-92709.patch

* zephyr: patches: include changes from pr 92709
* manifest: switch to zephyr v4.2.0-rc3
Note: PR 92709 was previously approved by the maintainer and is now being held up for philosophical reasons by someone who is not the maintainer. I don't think we should release tt-zephyr-platforms FW without it though.

manifest: switch to zephyr v4.2.0-rc3

---

drivers/misc/bh_fwtable/bh_fwtable.c

Return fake table if FW table loading fails to prevent NULL pointer access

fw_table: prevent NULL pointer access

---

MAINTAINERS.yml

We don't have an official "release team" in TT GitHub, but we should, since it's a role that can be rotated semi-regularly. The upstream release team have triage and merge privileges, whereas maintainers and contributors have approval privileges.
In any case, Daniel completed the release for Zephyr v4.2.0, so he can be added to the Tenstorrent release team.

MAINTAINERS: add danieldegrasse to release team

---

README.md

Based on user feedback, fix up the readme to
1. output tt-console in a consistent location
2. use a board other than p100 (p100a is a safer base configuration)
3. note that users should change their board for different board revisions
4. add a note / link about using a patched version of openocd

readme: additional fixes for readme based on user feedback

---

README.md

On a fresh clone, `west blobs fetch` will fail because the python requests library is not present, so install python packages before running that command.
I should specify, that I kind of half-followed the Zephyr GSG when performing a fresh install.
1. Start container
```shell
docker run --rm -it ubuntu:latest
```
2. Update packages (from GSG, without `sudo`)
```shell
apt update
apt upgrade
```
3. Install required utilities (from GSG, without `sudo` and multilib packages)
```shell
sudo apt install --no-install-recommends git cmake ninja-build gperf \
ccache dfu-util device-tree-compiler wget python3-dev python3-venv python3-tk \
xz-utils file make gcc libsdl2-dev libmagic1
```
4. Set up venv (modified from GSG)
```shell
python3 -m venv ~/tt-zephyr-platforms-work/.venv
source …
```

readme: install packages before fetching blobs

---

app/smc/pytest/vuart.py
scripts/tooling/console.c
scripts/tooling/vuart.c
scripts/tooling/vuart.h

* ensure that the virtual uart can still work between card resets and flashes.
* if the timeout parameter is specified, trigger `SIGALRM` via timer
Currently, even with a manual rescan of the pcie bus, `tt-console` does _not_ properly reconnect to the virtual uart. 
With this change, the gif below shows production firmware interleaved with the flash performance test output repeated twice (i.e. is able to reconnect to the virtual uart multiple times).

scripts: tooling: ensure tt-console works across flashes and rescans

---

.github/workflows/prepare-zephyr/action.yml
app/smc/tracing.overlay
boards/tenstorrent/tt_blackhole/init.c
drivers/mspi/mspi_dw.c

Add changes to improve the reliability of programming the P100 flash. These changes were tested in #243, but this PR removes the commit adding the test and only includes the fixes.

boards: tenstorrent: improve reliablity when programming P100 flash

---

app/smc/pytest/e2e_smoke.py
app/smc/sample.yaml

Add test for SPI read/write. This test should help catch issues with SPI access before we utilize tt-flash to write firmware, and will help catch any issues with the flash driver code

app: smc: pytest: add pytest for SPI read/write

---

LICENSE
LICENSE_understanding.txt
README.md

* Move non-Apache-2.0 binary blob license details out of the Apache-2.0 `LICENSE` file and into `README.md`
* Move the contents of `LICENSE_understanding.txt` into `README.md`

license: move non-apache licensing details to readme

---

.github/workflows/hardware-long.yml
.github/workflows/hardware-smoke.yml
.github/workflows/run-unit-tests.yml

Historically, `twister` has required the `--retry-failed` argument and friends because of extremely-difficult-to-guarantee synchronization between the host clock and the "hardware clock" in Qemu guests.
This is most prevalently seen when running kernel benchmarks, SMP locking, and SMP thread stress tests when running multiple SMP Qemu guests in parallel.
It reduces to the fact that one Qemu instance will make assumptions about host CPU availability that break down under heavy load. That causes jitter in the guest "hardware clock", typically on the order of a few ms or sometimes tens of ms.
We don't (yet) run those kinds of stress tests involving multiple Qemu targets in our CI, so retrying is really just exacerbating a problem, which is that if our hardware platform fails on the first try …

ci: do not retry if twister jobs fail

---

.github/workflows/hardware-long.yml
.github/workflows/hardware-smoke.yml
scripts/smc_console.py

We don't strictly *need* the hardware map file currently, as we only
have one DUT per test system. While the file represents a convenient way
to encode multiple flash options, it resides outside of version control
and has caused CI headaches in the past.
Encode twister run options directly into commands used in CI and use
tt-console built from source, so that all portions of the test are version
controlled.

ci: hardware: remove use of hardware-map definition

---

scripts/tooling/console.c
scripts/tooling/vuart.c

Within a container, failing to open the device /dev/tenstorrent/0 will fail with error code ENXIO because we have indicated to docker that /dev/tenstorrent/0 is a "special device" Add this errno code as a special case that triggers a rescan.
This should resolve lingering CI issues with smoke tests.

scripts: tooling: tt_console: fix rescan within container

---

app/smc/pytest/e2e_smoke.py
drivers/clock_control/clock_control_tt_bh.c

Set AICLK handler needs to account for the postdiv on the PLL clock
(defaults to 4) or the AICLK frequency will be set to a quarter of the
expected value.
Update the AICLK setter to handle the external postdiv.
Signed-off-by: Daniel DeGrasse <ddegrasse@tenstorrent.com>

drivers: clock_control: clock_control_tt_bh: fix set_aiclk handler

---

scripts/pre-push.sh

CI compliance checks now care about clang-format, so make the pre-push checks do the same.

scripts: pre-push: update to align with CI checks

---

scripts/tooling/console.c

Don't return error if select() syscall is interrupted by signal- this simply indicates that tt-console was started with the "-w" parameter and a timeout was hit.

scripts: tooling: console: don't return error if interrupted by signal

---

scripts/dmc_reset.py

Previously, if I ran `./scripts/dmc_reset.py`, I would see this on a p100 machine. Not sure if it's the same everywhere.
```shell
./scripts/dmc_reset.py
Failed to reset DMC: None
```
Expanding the verbosity (with `-d`), i was able to determine if i took out `-c 'adapter serial auto'`, then the command would work as expected.
It seems like there was a minor inconsistency with using the default value "auto". Removing it seems to make the script work reliably again.

scripts: dmc_reset: fix Failed to reset DMC None error

---

lib/tenstorrent/bh_arc/gddr.c

Adding comment for HW mem test to prevent HW test being removed

gddr: adding comment for HW test to prevent removal

---

doc/release/migration-guide-18.8.md
dts/arc/tenstorrent/tt_blackhole_smc.dtsi
dts/bindings/clock/tenstorrent,bh-clock-control.yaml
lib/tenstorrent/bh_arc/cat.c
lib/tenstorrent/bh_arc/cat.h
lib/tenstorrent/bh_arc/telemetry.c
lib/tenstorrent/bh_arc/telemetry.h

Get AICLK from firmware table instead of devicetree, and store VDD min and max in the VDD LIMITS tag.
cc @afongTT

lib: tenstorrent: bh_arc: telemetry.c: update aiclk and vdd telemetry

---

lib/tenstorrent/jtag_bootrom/jtag_bootrom.c

Add a print statement if PGOOD isn't high during boot. This should help diagnose cases where a card isn't enumerating because PGOOD has gone low, since CI will dump the DMC RTT logs.

lib: tenstorrent: add a print if PGOOD isn't high during boot

---

doc/release/migration-guide-18.8.md

Our CI requires that we [manually install a version of pyluwen that is explicitly > 0.7.9](https://github.com/tenstorrent/tt-zephyr-platforms/blob/7b1c0886df959cb26af514262de777faf19478aa/.github/workflows/prepare-zephyr/action.yml#L92).
The exact revision is `d20b8d6f64c0`, which is sometime after 0.7.9 according to [Cargo.toml](https://github.com/tenstorrent/luwen/blob/d20b8d6f64c06fe01f0734d1dd5c0a669f4fa29a/crates/pyluwen/Cargo.toml).
To be sure that we communicate to end users what the required minimum version of pyluwen is, suggest [the latest version available from pypi.org which is 0.7.11](https://pypi.org/project/pyluwen/0.7.11/).

doc: migration: 18.8: bump pyluwen to >= 0.7.11

---

doc/release/migration-guide-18.9.md
doc/release/migration-guide-19.0.md
doc/release/release-notes-19.0.md

Our next release, v19.0.0 will include a major version bump from 18 to 19 to account for the fact that the SPI flash and internal DMC flash layouts will be changed.

doc: release: rename 18.9 to 19.0 and adjust versions

---

dts/arc/tenstorrent/tt_blackhole_smc.dtsi
tests/boards/tenstorrent/tt_blackhole/clock_control/Kconfig
tests/boards/tenstorrent/tt_blackhole/clock_control/prj.conf
tests/boards/tenstorrent/tt_blackhole/clock_control/src/main.c

Test a wider range of frequencies for set AI and GDDR clock frequencies
Follow up to #462

tests: boards: tenstorrent: tt_blackhole: clock_control: test wider ranges

---

app/smc/src/main.c
include/tenstorrent/sys_init_defines.h
lib/tenstorrent/bh_arc/aiclk_ppm.c
lib/tenstorrent/bh_arc/arc_dma.c
lib/tenstorrent/bh_arc/avs.c
lib/tenstorrent/bh_arc/cat.c
lib/tenstorrent/bh_arc/eth.c
lib/tenstorrent/bh_arc/gddr.c
lib/tenstorrent/bh_arc/harvesting.c
lib/tenstorrent/bh_arc/msgqueue.c
lib/tenstorrent/bh_arc/noc_init.c
lib/tenstorrent/bh_arc/pcie.c
lib/tenstorrent/bh_arc/pll.c
lib/tenstorrent/bh_arc/pvt.c
lib/tenstorrent/bh_arc/regulator.c
lib/tenstorrent/bh_arc/reset.c
lib/tenstorrent/bh_arc/smbus_target.c
lib/tenstorrent/bh_arc/spi_eeprom.c
lib/tenstorrent/bh_arc/tensix_cg.c

It is painful currently to insert a SYS_INIT step between two steps, it requires manually editing all the files that does SYS_INIT. Centralizing SYS_INIT priorities so that only one file edit is needed.

sys_init: centralize sys_init prio

---

include/tenstorrent/tt_smbus_regs.h
lib/tenstorrent/bh_arc/smbus_target.c
tests/lib/tenstorrent/bh_arc/src/smbus_target.c

SMBUS spec indicates that, for block-write-block-read transactions, the PEC is only present on the end of the read phase (and covers all of the transaction.) The bug before was that we were also expecting a PEC byte during the write phase, which is incorrect.
Add a test command to cover this case and a testcase in native_sim.
Note this doesn't affect our ODM because all their commands have PEC = 0.

lib: tenstorrent: bh_arc: Fix BWBR PEC

---

include/tenstorrent/sys_init_defines.h
lib/tenstorrent/bh_arc/CMakeLists.txt
lib/tenstorrent/bh_arc/gddr.h
lib/tenstorrent/bh_arc/noc_dma.c
lib/tenstorrent/bh_arc/noc_dma.h
lib/tenstorrent/bh_arc/wipe_l1.c

It is requested to wipe L1 space during boot to protect user information.
In this MR, tensix, erisc and mrisc L1 are wiped.
https://tenstorrent.atlassian.net/browse/SYS-1631

Wipe all L1s for security

---

lib/tenstorrent/bh_arc/noc2axi.c
lib/tenstorrent/bh_arc/noc2axi.h
lib/tenstorrent/bh_arc/noc_dma.c

Commit d3cb9055 (security: wipe l1s, 2025-08-06) caused a regression by adding the NOC code in bh_arc into the bh_arc test built in simulation, since we now perform NOC access during system init.
Rather than reverting this commit, add support in the noc code for running within emulation. This support is *very* limited- we essentially create RAM buffers to fake out the NOC TLB and configuration spaces, and fake NOC completion where required. However, it is sufficient to fix the bh_arc tests.
Note that we need something like this, or need to revert d3cb9055 to fix CI

lib: tenstorrent: bh_arc: support running NOC code in native_sim

---

.github/workflows/hardware-long.yml
app/smc/pytest/e2e_smoke.py
app/smc/pytest/e2e_stress.py
app/smc/sample.yaml
scripts/dmc_reset.py
scripts/rtt_helper.py
scripts/tt_flash_runner.py

Fix a few issues affecting the reliability of the E2E stress test, notably:
> In some CI tests the DMC flash prior to running tt-flash will leave the
card in a state where a PCIe rescan is required. Add a pcie rescan step to
the tt-flash runner in order to improve CI reliability, and automate
this rescan for developers.
> In 3e74f74 (app: smc: improve code reuse in E2E stress test,
2025-08-15), code that waited for the DMC to set the PCIe init time
after booting the SMC was mistakenly dropped. This has caused the E2E
stress test to fail in the PCIe init phase.
> tt-kmd sets a 10000ms watchdog timer on the ARC after reset. In some
cases this overrides our watchdog timer. To work around this, delay an
additional 10 seconds if the SMC initially fails to reset, and log a
warning. Only fail …

ci: fixes for e2e-stress tests

---

doc/release/migration-guide-18.9.md
doc/release/migration-guide-19.0.md
doc/release/release-notes-18.9.md

Change release notes back to a minor version bump per the next planned version release.

doc: release: rename 19.0 to 18.9 and adjust versions

---

README.md

The previous getting started guide directed the user to rely on upstream zephyr's steps for setting up a python virtual environment and installing the SDK.
However, if these steps are followed to the letter the user will end up with a separate ~/zephyrproject folder with their virtual environment installed (and potentially zephyr as well, if they follow the entire guide).
IMO, it seems reasonable to duplicate portions of the getting started guide where we deviate from them. Another alternative would be to direct users to use the getting started guide, but substitute "~/zephyrproject" out with our module name wherever they see fit.

readme: update getting started instructions

---

.github/workflows/docs.yml
boards/index.rst
boards/tenstorrent/tt_blackhole/doc/index.rst
doc/Makefile
doc/conf.py
doc/index.rst

Deploy doc to github pages when pushed to main branch
For examples of this deployment, see
* https://danieldegrasse.github.io/tt-zephyr-platforms/
* https://cfriedt.github.io/tt-zephyr-platforms/ (minor corrections)

ci: doc: deploy to github pages

---

lib/tenstorrent/bh_arc/Kconfig

Change TT_BH_ARC_SCRATCHPAD_SIZE Kconfig to int instead of hex type, reducing the scratchpad size from 0x512 (1298) to 512.
This seems to have been causing eth FW loading issues on cold boot.

lib: tenstorrent: bh_arc: lower scratchpad size

---

include/tenstorrent/sys_init_defines.h
lib/tenstorrent/bh_arc/CMakeLists.txt
lib/tenstorrent/bh_arc/eth.c
lib/tenstorrent/bh_arc/gddr.c
lib/tenstorrent/bh_arc/noc_init.c
lib/tenstorrent/bh_arc/noc_init.h
lib/tenstorrent/bh_arc/reset.c
lib/tenstorrent/bh_arc/tensix_init.c
lib/tenstorrent/bh_arc/tensix_init.h

We use a tensix as the source of zeroes, and to run NOC DMAs. Because wiping happens before translation is enabled, we can't count on known-good tensixes at certain NOC coordinates. Instead we need to find the coordinates of an enabled tensix.

SYS-2023 Fix boot hang due to using disabled tensix to wipe L1s

---

zephyr/patches.yml
zephyr/patches/zephyr/smbus_stm32-pec.patch

The smbus PEC correction patch double sends the command byte. We need to only send it once according to spec.

patches: Fix smbus PEC correction patch

---

drivers/sensor/tenstorrent/pvt_tt_bh_decoder.c
include/zephyr/drivers/sensor/tenstorrent/pvt_tt_bh.h
lib/tenstorrent/bh_arc/pvt.c
tests/boards/tenstorrent/tt_blackhole/sensor/pvt/src/main.c

Namespace helper functions that convert between data types with pvt_tt_bh as they are in the global namespace. It is not possible to make them private/static as they are used by multiple files.

drivers: sensor: tenstorrent: pvt: tt_bh: namespace helper functions

---

zephyr/patches.yml
zephyr/patches/zephyr/twister-rtt-support.patch

Since we have `scripts/dmc_rtt.py` and `scripts/smc_console.py`, we no longer require the twister rtt patch (almost). Also, it was rejected upstream, so this is a good opportunity to shed tech debt.
However, the `--flash-before` logic is broken in twister on version 4.2.0. The good news is that it looks like it's fixed in `main` already.
Keep this smaller change in-tree until it is resolved nearer to upgrade time.

zephyr: patches: drop twister rtt patch, since we now have pty scripts

---

.github/workflows/release.yml

Since 49aacf6a3cb660f252a003b38a88296d9c1c4e03, the `tt-zephyr-platforms-<version>.zip` file that is created as a published release artifact, that contains build and debug information for all platforms, has only included a subdirectory for `p100`.
This is because the local variable was changed to a bash array `BOARD_REVS=(...)` but in the invocation of `zip`, the variable was evaluated as a normal variable rather than as a bash array.
Use `${BOARD_REVS[@]}` instead of `$BOARD_REVS` to have the variable evaluate to e.g. `p100 p100a p150a p150b p150c p300a p300b p300c galaxy` instead of only `p100`.
See [SYS-2054](https://tenstorrent.atlassian.net/browse/SYS-2054) for more information.

ci: release: ensure build artifacts for all board revisions are in zip

---

scripts/board_metadata.yaml
scripts/tooling/blackhole_recovery/recover-blackhole.py

Recovery scripting flashes ASICs in the order they are described, and
the left bootfs is the only one that contains the DMFW for P300 systems.
Define this asic first in metadata, so the board recovery scripting will
flash the DMFW during the initial recovery phase.
Signed-off-by: Daniel DeGrasse <ddegrasse@tenstorrent.com>

scripts: define left ASIC first for P300

---

scripts/tooling/vuart.c

During reset, a card may read as 0xffff_ffff until the card re-enumerates over pcie. In this case, return an error so the vuart tooling will rescan pcie.

scripts: tooling: vuart: report error if card reads as 0xffff_ffff

---

scripts/check-copyright.py
scripts/pre-commit.sh

Exclude subdirectories with "build" in the name, so the build folder for
the SPI FLM doesn't trigger the check.
Add ruff format/lint checks before commit, to catch errors earlier.

scripts: fixes for compliance checks

---

dts/arc/tenstorrent/tt_blackhole_smc.dtsi
zephyr/patches.yml
zephyr/patches/zephyr/arch-arc-core-support-multilevel-interrupt-priority.patch

Make the SPI interrupt highest priority. This will ensure that the SPI
controller is never preempted while writing to the SPI flash.
Should fix test issues like this one: [tenstorrent/tt-zephyr-platforms/actions/runs/17655677993/job/50180829826](https://github.com/tenstorrent/tt-zephyr-platforms/actions/runs/17655677993/job/50180829826)

dts: arc: tenstorrent: make SPI interrupt highest priority

---

.github/workflows/docs.yml
boards/tenstorrent/tt_blackhole/doc/index.rst
doc/conf.py
doc/develop/debugging/tracing.rst

Fix rendering of Zephyr app commands, and remove directives we aren't rendering at all

doc: fix rendering of zephyr-app-commands

---

.github/workflows/docs.yml
doc/conf.py
scripts/get_ttzp_version.py

Derive the version displayed in generated documentation from the release / bundle `VERSION` file at the root of the repository.
Testing Done:
```py
>>> ver = get_ttzp_version()
>>> print(ver)
18.11.0-rc1
>>> ver = get_ttzp_version()
>>> print(ver)
18.11.0
```
```shell
$ grep -Rn "18\.11\.0" deploy
...
deploy/doxygen/structtt__vuart.html:24:   <div id="projectname">TT Zephyr Platforms<span id="projectnumber">&#160;18.11.0-rc1</span>
...
```

doc: derive documentation version from bundle / release version

---

.github/workflows/hardware-long.yml
.github/workflows/hardware-smoke.yml
.github/workflows/prepare-container/action.yml
app/dmc/sysbuild/mcuboot.conf
app/smc/pytest/e2e_smoke.py
app/smc/pytest/e2e_stress.py
app/smc/pytest/vuart.py
boards/tenstorrent/tt_blackhole/board.cmake
scripts/dmc_rtt.py
scripts/dump_smc_state.py
scripts/smc_test_recovery.py
soc/tenstorrent/tt_blackhole/CMakeLists.txt
soc/tenstorrent/tt_blackhole/soc.c
zephyr/patches.yml
zephyr/patches/zephyr/scripts-pylib-pytest-twister-harness-ensure-serial.patch
zephyr/patches/zephyr/scripts-twister-add-failure_script-parameter-to-run.patch

Add two crash handlers:
- a custom version of k_sys_fatal_error_handler
- a custom reset handler
Both crash handlers will log the system BLINK (crash address) into ICCM
at address 0x0000_0004. The reset handler will execute if the ARC
inadvertently triggers a soft reset, and the fatal error handler will
execute for cases that Zephyr considers a fatal exception.
Additionally, add a script to dump SMC state after a crash. This script will be run after a failure in pytest or CI as a whole, and can help us debug a crash on the ARC core.
Finally, exit pytest if the DUT fails to flash or enumerate. This will reduce log verbosity, since if the ARC fails to enumerate there is no point running the pytests and getting a bunch of errors.
Add CI steps to log the machine state, so that we can more …

improvements for test error reporting

---

doc/release/migration-guide-18.10.md
doc/release/migration-guide-18.11.md
doc/release/migration-guide-18.2.md
doc/release/migration-guide-18.3.md
doc/release/migration-guide-18.4.md
doc/release/migration-guide-18.5.md
doc/release/migration-guide-18.6.md
doc/release/migration-guide-18.7.md
doc/release/migration-guide-18.8.md
doc/release/migration-guide-18.9.md
doc/release/release-notes-18.11.md

We didn't manually add release notes in this sprint unfortunately, so use and modify GitHub's automatically-generated release notes.
Also added level-2 heading to distinguish the Migration Guide from Release Notes, along with some other drive-by cleanups.

doc: release: 18.11: add release notes based on github changelog

---

scripts/tooling/blackhole_recovery/recover-blackhole.py

Add more status messages to blackhole recovery scripting and increase
delays. This should help debug cases where ASIC recovery fails.
Additionally, first try to reset the DMC before we flash it. This should provide some performance improvements in CI.
Make the recovery script fully erase the flash before writing to it. This should make sure the card is in a known state after recovery, improving stability of the script.

scripts: blackhole_recovery: add more status messages, increase delays

---

.github/workflows/build-fw.yml

build-fw needs a different concurrency group since other jobs depend on it. Otherwise github actions will error out with the message "a deadlock was detected for concurrency group"

ci: build-fw: fix concurrency group name

---

app/smc/pytest/e2e_smoke.py
app/smc/pytest/e2e_stress.py

Reduce the verbosity on some of the tests that execute e.g. 1000 times (although failures are still always logged).
Additionally, add a `failure_fail_count` as a threashold for group failure rate for repeated tests. For most tests, a single failure is still enough to fail the test but for some 10 / 1000 is probably a good threshold, since several tests fail when 1 or 2 of 1000 iterations fail.
10 / 1000 is a failure rate of 1%, so if we pass with a 0.1% or 0.2% failure rate (1 or 2/1000), it's probably still safe.

app: smc: pytest: modify verbosity and use failure rate

---

app/dmc/src/main.c
include/tenstorrent/event.h
lib/tenstorrent/bh_chip/bh_chip.c
lib/tenstorrent/event/event.c
lib/tenstorrent/jtag_bootrom/jtag_bootrom.c

Create a distinct event for each activity in the DMC main loop. Slow activities check the signalled event bitmap. Some activities still have flags in the chip object to know when they've been triggered.
This is in preparation to move ia228_power_update to 1ms frequency. Fan update and CM2DM will stay at 20ms.

Fine-grained DMC events

---

boards/tenstorrent/tt_blackhole/spirom_data_tables/GALAXY/fw_table.txt

Enable AICLK PPM on Galaxy, setting the following limits:
- TDP = 170 W
- Fast TDC = 400 A
- TDC = 500 A (effectively disabled)

fw_table: enable aiclk ppm for Galaxy

---

app/smc/pytest/e2e_stress.py

Check if failure rate is less than or equal to threshold, rather than strictly less than. This allows us to limit the max iterations of the e2e-stress test locally (by changing the MAX_ITERATIONS variable) and still get useful feedback. Without this change, the failure_fail_count value will be set to 0 in some cases, and then assertions will fail even if the test failed zero times.

app: pytest: e2e_stress: use zero based failure checks

---

lib/tenstorrent/bh_chip/bh_chip.c
zephyr/patches.yml
zephyr/patches/zephyr/smbus_stm32-pec.patch

Add rate-limited logging of PEC errors maximally once per second. This should help to diagnose link quality issues.
Log output:
```shell
[00:00:01.517,000] <err> stm32_smbus: smbus3: PEC error. expected: ff actual: 9c total: 41 errors: 1
[00:00:09.197,000] <err> stm32_smbus: smbus3: PEC error. expected: ff actual: 9c total: 464 errors: 2
[00:00:17.377,000] <err> stm32_smbus: smbus3: PEC error. expected: ff actual: 9c total: 913 errors: 3
[00:00:20.617,000] <err> stm32_smbus: smbus3: PEC error. expected: ff actual: 9c total: 1091 errors: 4
[00:00:23.657,000] <err> stm32_smbus: smbus3: PEC error. expected: ff actual: 9c total: 1258 errors: 5
[00:00:25.957,000] <err> stm32_smbus: smbus3: PEC error. expected: ff actual: 9c total: 1384 errors: 6
```

drivers: smbus: stm32: add rate-limited logging of PEC errors

---

boards/tenstorrent/tt_blackhole/tt_blackhole_tt_blackhole_dmc_p300a.overlay

Reduce P300 I2C clock speeds to 100KHz. This resolves periodic SMBUS errors logged by the STM32, at the cost of some I2C performance

boards: tenstorrent: reduce p300 I2C clock speeds

---

.github/workflows/hardware-long.yml

Fix e2e-stress script invocation so that tests will actually run
Signed-off-by: Daniel DeGrasse <ddegrasse@tenstorrent.com>

ci: fix e2e-stress invocation
