- .gitignore
- app/smc/sysbuild.cmake
- scripts/manual-release.sh
- scripts/tt_boot_fs.py
* scripts: tt_boot_fs: add support for combining fwbundle files
* add manual release script
> scripts: add manual release script

- lib/tenstorrent/bh_arc/vf_curve.c
- lib/tenstorrent/bh_arc/voltage.c
Update the frequency to voltage relationship based on latest gathered data.
> tenstorrent: bh_arc: update vf curve

- lib/tenstorrent/bh_arc/regulator.c
modify serdes vr rails switching frequency to maximum on p150, p300, and Galaxy
We skip serdes_vdd on p300 left, because left and right share serdes_vdd, only right has i2c connection to serdes_vdd.
> Increase VR switching freq

- .gitignore
Splitting change from https://github.com/tenstorrent/tt-zephyr-platforms/pull/32
> git: Update git ignore to ignore tt-console program

- README.md
Add instructions for building app/smc with the vuart overlay, and using tt-console to observe console output.
> readme: add instructions for using tt-console

- README.md
Remove unnecessary note about app overlays.
> readme: remove unnecessary note about app overlays

- scripts/tt_boot_fs.py
Add support for outputting the tt_boot_fs in hex format, for cases where the image will be flashed directly (IE via JTAG)
> scripts: tt_boot_fs: add support for output in hex format

- doc/release.md
Elaborate on the stabilization period before release (aka feature freeze), add a section regarding exceptions and seeking approval by the Change Review Board (CRB).
Additionally, elaborate on the Release Checklist.
This process is based on the Zephyr release process and also the release process used in many other Open Source projects.
https://docs.zephyrproject.org/latest/project/release_process.html
> doc: release: elaborate on stabilization period and feature feeze

- .github/ISSUE_TEMPLATE/001_bug_report.md
- .github/ISSUE_TEMPLATE/002_enhancement.md
- .github/ISSUE_TEMPLATE/003_rfc-proposal.md
- .github/ISSUE_TEMPLATE/004_feature_request.md
Add issue templates from the Zephyr project for bug, enhancement, rfc, and feature request issues.
Closes #102
> github: add issue templates for bug, enhancement, rfc, and feature req

- .github/workflows/hardware-long.yml
Add a small set of tests from tt-metal that have a good chance of working correctly and do not require additional setup.
> Add new tests experimentally

- scripts/tt_boot_fs.py
Add extract command to tt_boot_fs utility, to extract a binary corresponding to a tag from an existing tt_boot_fs binary
> scripts: tt_boot_fs: add extract subcommand

- lib/tenstorrent/bm_event/bm_event.c
Clear bm events everytime after waiting bm events.
> bm_event: clear bm events after wait events

- .github/workflows/hardware-smoke.yml
- scripts/bmc_rtt.py
- scripts/rtt_helper.py
- scripts/smc_rtt.py
Add step to CI to dump RTT data to STDOUT on job failure- this should hopefully help with debugging CI failures in the future
> ci: add step to dump RTT data if hardware test fails

- app/smc/pytest/e2e_smoke.py
Add a more robust algorithm to scan for the PCIe card to return to the bus. Should help with a few classes of errors:
- SMC firmware is taking longer than expected to init
- PCIe card is not present on bus and needs a manual rescan to reappear
> app: smc: make e2e smoke test more robust

- .github/workflows/build-fw.yml
Save artifact from build-fw.yml
Signed-off-by: Kannika Kabilar kkabilar@tenstorrent.com
> Save the uploaded artifact as github output

- doc/release/release-notes-18.3.0.md
My contribution to 18.3.0 release notes.
> doc: release: update contents of 18.3.0 release notes

- doc/release/migration-guide-18.4.0.md
- doc/release/release-notes-18.4.0.md
Create a template for release notes for the upcoming v18.4.0 firmware release.
> doc: release: v18.4.0: add template release notes

- .github/workflows/build-fw.yml
- app/smc/sysbuild.cmake
- boards/tenstorrent/tt_blackhole/board.yml
- boards/tenstorrent/tt_blackhole/bootfs/galaxy-bootfs.yaml
- boards/tenstorrent/tt_blackhole/revision.cmake
- boards/tenstorrent/tt_blackhole/spirom_data_tables/GALAXY/fw_table.txt
- cmake/bootfs_util.cmake
- scripts/build-combined-fwbundle.sh
Added galaxy board type to bootfs
https://tenstorrent.atlassian.net/browse/SYS-1513
> bh_arc: added galaxy board type to bootfs

- .github/workflows/hardware-smoke.yml
Call build-fw in hardware-smoke
Integrate build-fw into hardware-smoke
Signed-off-by: Kannika Kabilar <kkabilar@tenstorrent.com>
> Integrate build-fw into hardware-smoke

- app/dmc/src/main.c
- include/tenstorrent/bh_chip.h
- lib/tenstorrent/jtag_bootrom/jtag_bootrom.c
- lib/tenstorrent/jtag_bootrom/reset.c
1. Bug fix for p300 straps not being set correctly
- d576437de5fadf38b6eaf820c58a1cebd74eff5b
- 385cfa780874b823f096ef078e2969a043a1d7a0
> Backport of p300 support to 18.3

- scripts/pcie_utils.py
In certain CI jobs that are run inside of a privileged container, processes run as root so there are never any permission issues.
As a user e.g. on a lab machine, when attempting to reproduce CI failures, we don't have the same permission, but we do want the scripts to succeed anyway.
This is particularly true when trying reproduce a failure with twister the usual way (by copying and modifying the repro-recipe that twister prints).
Echo bits to the `remove` and `rescan` nodes as root via sudo.
See also https://github.com/tenstorrent/tt-zephyr-platforms/issues/269
> scripts: pci_utils: support removing and rescanning the bus via sudo

- doc/release/release-notes-18.5.0.md
Add a few missing release note entries.
> doc: release: minor tweaks to release notes for v18.5.0

- boards/tenstorrent/tt_blackhole/spirom_data_tables/P300A_L/read_only.txt
- boards/tenstorrent/tt_blackhole/spirom_data_tables/P300A_R/read_only.txt
- boards/tenstorrent/tt_blackhole/spirom_data_tables/P300B_L/read_only.txt
- boards/tenstorrent/tt_blackhole/spirom_data_tables/P300B_R/read_only.txt
- boards/tenstorrent/tt_blackhole/spirom_data_tables/P300C_L/read_only.txt
- boards/tenstorrent/tt_blackhole/spirom_data_tables/P300C_R/read_only.txt
- doc/release/release-notes-18.6.0.md
- lib/tenstorrent/bh_arc/read_only_table.c
- lib/tenstorrent/bh_arc/read_only_table.h
- lib/tenstorrent/bh_arc/regulator.c
- lib/tenstorrent/bh_arc/telemetry.c
change definition of left right chip for Ethernet training or read only table.
> SPI: asic_location

- .github/workflows/cleanup-branches.yml
Add nightly action to remove feature branches. Keep main and version branches.
Just outputting the branch names for now, and once confirmed it works, then I'll add the actual deletion
Fixes: #292
> .github: workflows: Add nightly action to remove feature branches

- scripts/tt-console/console.c
As of kmd 1.34+ tt-kmd provides an API for allocating TLBs instead of manually mapping the PCIe bar space. This gives us the ability to run alongside other programs that wish to also interact with the hardware.
This patch adds support for this capability and removes support for the older manually mapped TLBs.
> Updated tt-console to use the kmd tlb allocation API

- .github/workflows/release.yml
Le sigh...
Successful workflow where this is running
https://github.com/cfriedt/tt-zephyr-platforms/actions/runs/16063118493
> ci: release: embed quotes in quotes so output of jq is quoted

- drivers/watchdog/wdt_tt_bh.c
- include/tenstorrent/bh_arc.h
- lib/tenstorrent/bh_arc/cm2dm_msg.c
- lib/tenstorrent/bh_arc/cm2dm_msg.h
- lib/tenstorrent/bh_arc/init.c
Replace the CM2DM message queue with a vector of possible messages.
Other minor cleanups.
> Improve CM2DM robustness

- boards/tenstorrent/tt_blackhole/tt_blackhole_tt_blackhole_dmc_p100.overlay
Enable octal boot mode for P100 card
> boards: tenstorrent: p100: enable octal boot mode

- boards/tenstorrent/tt_blackhole/bootfs/preflash-bootfs.yaml
- scripts/build-preflash.sh
added script to create preflash image for Quanta assembly
> Automate preflash image creation

- README.md
Update README.md with Zephyr v4.2.0 and more recent SMC and DMC app versions.
Also add a nice gif that shows off using the Zephyr shell on SMC.
> [!NOTE]  
> Compliance is failing because the gif is too large, but I think we can probably ignore that.
> readme: add a gif showing the zephyr shell and update to v4.2.0

- .github/workflows/hardware-long.yml
- .github/workflows/hardware-smoke.yml
Just another good thing: move up tests to be more updated
> ci: further uplift metal tests to v0.61

- README.md
- scripts/tooling/Makefile
- scripts/tooling/vuart.c
* scripts: tooling: vuart: mitigate warning / error about print format
* scripts: tooling: makefile: add all target and support output directory
* readme: update instructions for building tt-console
> readme: update instructions for building tt-console

- README.md
* remove comments re convenience variables and convenience variables
* move testing to its own section
> readme: remove convenience variables, make a separate test section

- include/tenstorrent/tt_smbus_regs.h
- lib/tenstorrent/bh_arc/asic_state.c
- lib/tenstorrent/bh_arc/asic_state.h
- lib/tenstorrent/bh_arc/smbus_target.c
- tests/lib/tenstorrent/bh_arc/src/smbus_target.c
Add command and tests to allow updating the ARC state via SMBUS.
> lib: tenstorrent: bh_arc: SMBUS command to update ARC state

- scripts/tooling/rescan.c
In pcie_walk_sysfs function, instead of using manual readdir() and having to handle recursion and errors -> utilizing the nftw function which handles tree-walking logic and still has a callback based API
> scripts: tooling: rewriting pcie_walk_sysfs

- app/smc/pytest/e2e_smoke.py
- app/smc/pytest/e2e_stress.py
Improve code reuse in E2E stress test. This is in response to a few
duplicated code sections flagged by pylint when updating the E2E stress
test for the ARC watchdog.
Signed-off-by: Daniel DeGrasse <ddegrasse@tenstorrent.com>
> app: smc: improve code reuse in E2E stress test

- lib/tenstorrent/bh_chip/strapping.c
add i2c recovery after failed strap configuration for gpio6
> lib: bh_chip: add i2c recovery after failed strap configuration

- .github/workflows/docs.yml
- doc/conf.py
* doc: conf: use read-the-docs theme for sphinx document generation
* ci: doc: rename genindex.html to index.html and cleanup
> doc: conf: use read-the-docs theme for sphinx document generation

- lib/tenstorrent/bh_arc/spi_eeprom.c
continuation of [https://github.com/tenstorrent/tt-zephyr-platforms/pull/503]
> Refactor spi eeprom

- scripts/tt_boot_fs.py
Add hexdump functionality when verbosity is greater than or equal to 2.
This helps to investigate firmware contents without pulling out `hexedit`.
This functionality only works when not using JSON output.
```shell
./scripts/tt_boot_fs.py ls -vvv build/tt_boot_fs.bin | less
spi_addr  image_tag size copy_dest data_crc flags    fd_crc
--------------------------------------------------------------------------
14000  cmfwcfg   72   00000000  8487c905 00000048 fc56dd13
14000  08 80 c6 a9 90 01 12 1b 08 c6 0a 10 84 07 18 bc   |................
14010  05 20 32 28 96 01 30 c8 01 38 5a 40 dc 01 60 a0   |. 2(..0..8Z@..`.
14020  06 68 55 1a 0a 08 01 10 01 18 01 20 01 38 01 22   |.hU........ .8."
14030  00 2a 00 32 00 3a 00 42 04 30 01 38 02 4a 05 08   |.*.2.:.B.0.8.J..
14040  ff 7f 10 01 52 00 00 01 …
```
> scripts: tt_boot_fs: ls: add hexdump functionality when verbose >= 2

- app/dmc/prj.conf
- boards/tenstorrent/tt_blackhole/tt_blackhole_dmc.dtsi
- boards/tenstorrent/tt_blackhole/tt_blackhole_tt_blackhole_dmc.dts
- boards/tenstorrent/tt_blackhole/tt_blackhole_tt_blackhole_dmc_p100.overlay
- boards/tenstorrent/tt_blackhole/tt_blackhole_tt_blackhole_dmc_p300a.overlay
- dts/arc/tenstorrent/tt_blackhole_smc.dtsi
- test-conf/tests/drivers/pwm/pwm_api/boards/tt_blackhole_tt_blackhole_dmc.overlay
- tests/boards/tenstorrent/tt_blackhole/dmc/gpiox/src/main.c
- tests/boards/tenstorrent/tt_blackhole/dmc/gpiox/testcase.yaml
DMFW produces a bunch of error logs when starting. Make the necessary board changes to remove these.
> app: dmc: clean up logging

- doc/develop/getting_started/index.rst
Add a tip on reapplying patches when pulling from main.
> doc: add snippet on pulling new code from main

- scripts/dump_smc_stack.py
AI created script to dump stacks. Can hexdump the full stack, or try to do symbol analysis based on where it thinks the TCB and current stack offset is.
> scripts: dump_smc_stack.py

- lib/tenstorrent/bh_chip/bh_chip.c
- zephyr/patches.yml
- zephyr/patches/zephyr/smbus-cancel.patch
- zephyr/patches/zephyr/smbus_stm32-pec.patch
- zephyr/patches/zephyr/stm32-bwbr.patch
Use the SMBus PEC patch as it has been submitted in https://github.com/zephyrproject-rtos/zephyr/pull/96691.
> zephyr: patches: use smbus pec patch as it is in upstream pr
